"""m1 core schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 07:02:35.068738

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "principals",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("auth_provider", sa.String(length=64), nullable=False),
        sa.Column("auth_subject", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principals")),
        sa.UniqueConstraint(
            "auth_provider",
            "auth_subject",
            name=op.f("uq_principals_auth_provider_auth_subject"),
        ),
    )
    op.create_table(
        "run_config_snapshots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("engine_installation_id", sa.String(length=32), nullable=True),
        sa.Column("capability_manifest_hash", sa.String(length=128), nullable=True),
        sa.Column("agent_profile_version_id", sa.String(length=32), nullable=True),
        sa.Column("agent_slots_json", sa.JSON(), nullable=False),
        sa.Column("provider_model_assignments_json", sa.JSON(), nullable=False),
        sa.Column("reasoning_tool_settings_json", sa.JSON(), nullable=False),
        sa.Column("engineering_preferences_json", sa.JSON(), nullable=False),
        sa.Column("skill_identities_json", sa.JSON(), nullable=False),
        sa.Column(
            "environment_profile_version_id", sa.String(length=32), nullable=True
        ),
        sa.Column("permitted_credential_refs_json", sa.JSON(), nullable=False),
        sa.Column("starting_git_commit", sa.String(length=64), nullable=True),
        sa.Column("starting_git_dirty", sa.Boolean(), nullable=False),
        sa.Column("starting_git_status_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_config_snapshots_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_config_snapshots")),
        sa.UniqueConstraint("run_id", name=op.f("uq_run_config_snapshots_run_id")),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column(
            "control_state",
            sa.Enum(
                "QUEUED",
                "STARTING",
                "RUNNING",
                "WAITING_FOR_HUMAN",
                "STOP_REQUESTED",
                "STOPPED",
                "FAILED",
                "COMPLETED",
                name="run_control_state",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("current_stage_category", sa.String(length=64), nullable=True),
        sa.Column("current_stage_native_id", sa.String(length=128), nullable=True),
        sa.Column("current_stage_label", sa.String(length=128), nullable=True),
        sa.Column("current_stage_order", sa.Integer(), nullable=True),
        sa.Column("active_work_item_id", sa.String(length=32), nullable=True),
        sa.Column("effective_config_snapshot_id", sa.String(length=32), nullable=True),
        sa.Column("engine_installation_id", sa.String(length=32), nullable=True),
        sa.Column("environment_snapshot_id", sa.String(length=32), nullable=True),
        sa.Column("active_attempt_id", sa.String(length=32), nullable=True),
        sa.Column("pending_interaction_id", sa.String(length=32), nullable=True),
        sa.Column("last_event_sequence", sa.Integer(), nullable=False),
        sa.Column("last_verified_state_id", sa.String(length=32), nullable=True),
        sa.Column("failure_class", sa.String(length=64), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column(
            "recoverability",
            sa.Enum(
                "RESUMABLE",
                "RETRYABLE_AS_NEW_RUN",
                "NOT_AUTOMATICALLY_RECOVERABLE",
                "UNKNOWN",
                name="recoverability",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["effective_config_snapshot_id"],
            ["run_config_snapshots.id"],
            name=op.f("fk_runs_effective_config_snapshot_id_run_config_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_runs_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint(
            "project_id", "ordinal", name=op.f("uq_runs_project_id_ordinal")
        ),
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("actor_principal_id", sa.String(length=32), nullable=False),
        sa.Column("command_type", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=32), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "ACCEPTED",
                "PROCESSING",
                "APPLIED",
                "FAILED",
                name="command_state",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("request_hash", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_summary", sa.Text(), nullable=True),
        sa.Column("result_refs_json", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_principal_id"],
            ["principals.id"],
            name=op.f("fk_commands_actor_principal_id_principals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commands")),
        sa.UniqueConstraint(
            "actor_principal_id",
            "command_type",
            "idempotency_key",
            name=op.f("uq_commands_actor_principal_id_command_type_idempotency_key"),
        ),
    )
    op.create_table(
        "execution_attempts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "ALLOCATED",
                "STARTING",
                "ACTIVE",
                "SUSPENDED",
                "EXITED",
                "LOST",
                name="attempt_state",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("worker_runtime_ref", sa.String(length=255), nullable=True),
        sa.Column("engine_installation_id", sa.String(length=32), nullable=True),
        sa.Column("environment_snapshot_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_reason", sa.String(length=64), nullable=True),
        sa.Column("observed_stage_category", sa.String(length=64), nullable=True),
        sa.Column("observed_engine_state_ref", sa.String(length=255), nullable=True),
        sa.Column("log_stream_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_execution_attempts_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_attempts")),
        sa.UniqueConstraint(
            "run_id", "ordinal", name=op.f("uq_execution_attempts_run_id_ordinal")
        ),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("principal_id", sa.String(length=32), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("canonical_path", sa.String(length=512), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=128), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_resource_ref", sa.String(length=64), nullable=True),
        sa.Column("response_snapshot_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
            name=op.f("fk_idempotency_records_principal_id_principals"),
        ),
        sa.PrimaryKeyConstraint(
            "principal_id",
            "method",
            "canonical_path",
            "idempotency_key",
            name=op.f("pk_idempotency_records"),
        ),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "origin_type",
            sa.Enum(
                "NEW_IDEA",
                "GITHUB_REPOSITORY",
                "OTHER_REPOSITORY",
                name="origin_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("origin_metadata_json", sa.JSON(), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=True),
        sa.Column(
            "workspace_status",
            sa.Enum(
                "INITIALIZING",
                "READY",
                "ERROR",
                name="workspace_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("workspace_error_code", sa.String(length=64), nullable=True),
        sa.Column("default_engine_policy_json", sa.JSON(), nullable=False),
        sa.Column(
            "default_agent_profile_version_id", sa.String(length=32), nullable=True
        ),
        sa.Column(
            "default_environment_profile_version_id",
            sa.String(length=32),
            nullable=True,
        ),
        sa.Column("engineering_preferences_json", sa.JSON(), nullable=False),
        sa.Column("current_verified_state_id", sa.String(length=32), nullable=True),
        sa.Column("current_run_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["principals.id"],
            name=op.f("fk_projects_owner_id_principals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "project_execution_leases",
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("attempt_id", sa.String(length=32), nullable=True),
        sa.Column("holder_id", sa.String(length=255), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("renewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_epoch", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["execution_attempts.id"],
            name=op.f("fk_project_execution_leases_attempt_id_execution_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_execution_leases_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_project_execution_leases_run_id_runs"),
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_project_execution_leases")),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("storage_driver", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "INITIALIZING",
                "READY",
                "ERROR",
                name="workspace_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workspaces_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("project_id", name=op.f("uq_workspaces_project_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspaces")
    op.drop_table("project_execution_leases")
    op.drop_table("projects")
    op.drop_table("idempotency_records")
    op.drop_table("execution_attempts")
    op.drop_table("commands")
    op.drop_table("runs")
    op.drop_table("run_config_snapshots")
    op.drop_table("principals")
    # ### end Alembic commands ###
