"""m2 event journal

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07 16:05:32.378989

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.String(length=32), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "CONTROL_PLANE",
                "RUN_COORDINATOR",
                "ENGINE_ADAPTER",
                "RUNTIME_MANAGER",
                "PREVIEW_CONTROLLER",
                "INTEGRATION",
                "SECURITY",
                name="event_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_event_sequence", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "DEBUG",
                "INFO",
                "WARNING",
                "ERROR",
                name="event_severity",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("stage_category", sa.String(length=64), nullable=True),
        sa.Column("stage_native_id", sa.String(length=128), nullable=True),
        sa.Column("stage_label", sa.String(length=128), nullable=True),
        sa.Column("stage_order", sa.Integer(), nullable=True),
        sa.Column("work_item_id", sa.String(length=32), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload_version", sa.Integer(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("artifact_ids_json", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["execution_attempts.id"],
            name=op.f("fk_events_attempt_id_execution_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_events_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint(
            "attempt_id",
            "source_event_sequence",
            name=op.f("uq_events_attempt_id_source_event_sequence"),
        ),
        sa.UniqueConstraint(
            "run_id", "sequence", name=op.f("uq_events_run_id_sequence")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
