from enum import StrEnum


class WorkspaceStatus(StrEnum):
    INITIALIZING = "INITIALIZING"
    READY = "READY"
    ERROR = "ERROR"


class RunControlState(StrEnum):
    QUEUED = "QUEUED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
    STOP_REQUESTED = "STOP_REQUESTED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class Recoverability(StrEnum):
    RESUMABLE = "RESUMABLE"
    RETRYABLE_AS_NEW_RUN = "RETRYABLE_AS_NEW_RUN"
    NOT_AUTOMATICALLY_RECOVERABLE = "NOT_AUTOMATICALLY_RECOVERABLE"
    UNKNOWN = "UNKNOWN"


class AttemptState(StrEnum):
    ALLOCATED = "ALLOCATED"
    STARTING = "STARTING"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    EXITED = "EXITED"
    LOST = "LOST"


class CommandState(StrEnum):
    ACCEPTED = "ACCEPTED"
    PROCESSING = "PROCESSING"
    APPLIED = "APPLIED"
    FAILED = "FAILED"


class EngineInstallationStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    SUPPORTED = "SUPPORTED"
    DEPRECATED = "DEPRECATED"
    BLOCKED = "BLOCKED"


class EngineRuntimeState(StrEnum):
    INITIALIZING = "INITIALIZING"
    READY = "READY"
    ERROR = "ERROR"


class CompatibilityStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"


class OriginType(StrEnum):
    NEW_IDEA = "NEW_IDEA"
    GITHUB_REPOSITORY = "GITHUB_REPOSITORY"
    OTHER_REPOSITORY = "OTHER_REPOSITORY"


class EventSource(StrEnum):
    CONTROL_PLANE = "CONTROL_PLANE"
    RUN_COORDINATOR = "RUN_COORDINATOR"
    ENGINE_ADAPTER = "ENGINE_ADAPTER"
    RUNTIME_MANAGER = "RUNTIME_MANAGER"
    PREVIEW_CONTROLLER = "PREVIEW_CONTROLLER"
    INTEGRATION = "INTEGRATION"
    SECURITY = "SECURITY"


class EventSeverity(StrEnum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
